### ISSUE TITLE
启动一直restarting，看不了日志

### ISSUE THREAD

**Issue by hywlzx** [accors/surgio-docker#1]
docker-compose配置如下：
```yml
version: '3.7'
services:
  surgio:
    image: accors/surgio:latest
    container_name: surgio-docker
    restart: unless-stopped
    environment:
      - REPO_URL="git@github.com:hywlzx/surgio.git"
      #- PNPM_SOURCE=安装依赖时使用的PNPM源，默认设置为npmjs官方源，可自定义
      - REPO-DOMAIN="github.com"
      - REPO-BRANCH="main"
      - KEY="" //具体的私钥删掉了
    ports:
      - "13001:3000" #默认gateway指定内部监听端口3000，若需修改则自己修改Surgio配置仓库中的gateway.js，并修改：后的端口号。
    volumes:
      - "/volume1/docker/portainer/data/etc/surgio:/surgio" #默认映射文件夹的根目录下surgio文件夹为主目录
```

一启动就自动重启，也没有打印任何的日志，不知道是什么问题
